name: GlobalQuestPlugin
main: com.github.doodlez.bukkit.globalquest.GlobalQuestPlugin
version: 0.0.1
commands:
  dome:
    description: Toggles glass over the airbase for Isaak Breen.
    usage: /dome
  givediary:
    description: Gives Isaak's diary number X.
    usage: /diary